### ISSUE TITLE
CSV Export, delimiter choice

### ISSUE THREAD

**Issue by RyanDou** [dbca-wa/wastd#339] opened 2020-09-16 07:49 UTC
## Problem

Every delimiter choice when going to export as csv is used in the data to be exported at some point. If you choose '|' it is used in the polymorphic_ctype column for 'observations | Turtle Nest Encounter'. Then ',' is used in some of the answers chosen in ODK, for example 'track, checked for nest, unsure if nest', ';' is used in the 'where' column 'SRID=4326;POINT (118.6088333333 -20.3077533333)' and ':' is used in the 'source_id' column 'uuid:836df1bf-d180-4460-bf42-5b1846cd51bc' leaving no delimiter that doesn't break the structure.
## Reproducible example
Export the first 100 observations under this link and each of the 4 delimiters will occur: https://wastd.dbca.wa.gov.au/admin/observations/turtlenestencounter/

**Comment by florianm** [comment] 2020-09-17 01:43
Using an "escapechar", e.g. `\`, solves this problem. Closing this issue as duplicate of #340 
Required action: update docs on using an escapechar, investigate whether django-admintools lets us set `\` as default escapechar.

**Closed by florianm** 2020-09-17 01:43 UTC
Labels: bug
